version: '2'
services:
  brandenportalserver-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/BrandenPortalServer/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=BrandenPortalServer
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
